name: protocol-env

on:
  workflow_dispatch:

PROTOCOL_ALIAS: pivot
RAW_URL: https://raw.githubusercontent.com

jobs:
  run-env:
    runs-on: ubuntu-latest
    steps:

      - name: loads GITHUB_ENV and GITHUB_PATH
        env:
          UN: ${{ var.USER0_NAME }}
          O: ${{ github.repository_owner }}
          RN: ${{ github.event.repository.name }}
          R: ${{ github.repository }}

        run: |
          echo "LE_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
          echo "USDER0_NAME=$UN" >> $GITHUB_ENV
          echo "OWNER=$O" >> $GITHUB_ENV
          echo "REPOSITORY_NAME=$RN" >> $GITHUB_ENV
          echo "REPOSITORY=$R" >> $GITHUB_ENV
