PROTOCOL_ALIAS: pivot
RAW_URL: https://raw.githubusercontent.com
DATE_FMT: "%Y-%m-%"

# env you need to run the dapps from pivoteur/protocol:

# ${{ var.USER0_NAME }}
# ${{ sec.USER0_EMAIL }}

# the YML files should use the following context expressions from github:

# ${{ github.repository_owner }}
# ${{ github.event.repository.name }}
# ${{ github.repository }}
