name: clothes

on:
  workflow_dispatch:
    inputs:
      index:
        description: 'ix'
        required: true
        default: '1'
      tx_id:
        description: 'tx_id'
        required: true
        default: 'asdf'
      actual_val:
        description: 'new_to_actual'
        required: true
        default: '0'

permissions:
  contents: write

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Run Sexy Man Test
        # This will trigger the "hello paris" logic
        run: cargo run -- sexy man

      - name: Run Best Boss Test
        # This will trigger the "That'll be the Dougster!" logic
        run: cargo run -- best boss ever
