name: daily

on:
  workflow_dispatch:
  schedule:
    - cron: "04 02 * * *" 

env:
  DAPP: quotes

permissions:
  contents: write

jobs:
  quotes-to-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout pivoteur.github.io
        uses: actions/checkout@v4

      - name: Load Shared Environment Variables
        uses: doughepi/yaml-env-action@v1.0.0
        with:
          files: .github/config/protocol-env.yml

      - name: Establish app path
        run: echo "DAPP_DIR=$DAPPS_DIR/$DAPP" >> $GITHUB_ENV

      - name: Establish git path
        run: echo "GIT_DAPP_DIR=$GITHUB_PATH/$DAPP_DIR" >> $GITHUB_ENV

      - name: Checkout protocol
        uses: actions/checkout@v4
        with:
          repository: pivoteur/protocol
          path: protocol

      - name: Checkout crypto-n-rust
        uses: actions/checkout@v4
        with:
          repository: logicalgraphs/crypto-n-rust
          path: crypto-n-rust

      - name: Cache quotes binary
        id: quotes-cache
        uses: actions/cache@v4
        with:
          path: protocol/dapps/quotes/target/release/quotes
          key: >-
           quotes-binary-
           ${{ hashFiles(format('{0}/quiz10/d_quotes/**/*.rs',
                                env.QUIZZES_SRC)) }}-
           ${{ hashFiles(format('{0}/Cargo.toml' env.DAPP_DIR)) }}-
           ${{ hashFiles(format('{0}/Cargo.lock', env.DAPP_DIR)) }}

      - name: Install Rust toolchain
        if: steps.quotes-cache.outputs.cache-hit != 'true'
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Build quotes
        if: steps.quotes-cache.outputs.cache-hit != 'true'
        run: |
          cargo build --manifest-path $DAPP_DIR/Cargo.toml --bin $DAPP --release

      - name: Add quotes and date to PATH
        run: |
          echo "$DAPP_DIR/target/release" >> $GITHUB_PATH
          echo "LE_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Run quotes
        run: $DAPP $LE_DATE > libs/quotes.json

      - name: Commit and push quotes.json
        env:
          USER0_NAME: ${{ vars.USER0_NAME }}
          USER0_EMAIL: ${{ secrets.USER0_EMAIL }}
        run: |
          git config --local user.email "$USER0_EMAIL"
          git config --local user.name "$USER0_NAME"
          git add libs/quotes.json
          git commit -m "Daily quotes JSON for $LE_DATE"
          git push
